# Exercicio 2 

Dados credit

Criar modelo utilizando todas variaveis e avaliar as principais, quais retiraria.

Retirar variaveis principais e criar outro modelo e verificar a diferença no erro

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [7]:

credit = pd.read_csv("http://www-bcf.usc.edu/~gareth/ISL/Credit.csv")
credit.columns

Index(['Unnamed: 0', 'Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education',
       'Gender', 'Student', 'Married', 'Ethnicity', 'Balance'],
      dtype='object')

In [21]:
credit = credit.drop(columns = 'Unnamed: 0' )
credit = pd.get_dummies(credit)

In [22]:
X = credit.drop(columns='Balance')
y = credit.Balance

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1 )
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print("Quantidade Observações:\nTreino: {tr}\nTeste: {te}\nValidação: {v}".format(tr = X_train.shape[0],
                                                                                 te = X_test.shape[0],
                                                                                 v = X_val.shape[0]))

Quantidade Observações:
Treino: 256
Teste: 80
Validação: 64


In [23]:
reg = LinearRegression()

In [24]:
reg.fit(X_train, y_train.values.reshape(-1,1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [48]:
pd.DataFrame(data = reg.coef_, columns = X.columns)

Income     Limit    Rating      Cards       Age  Education  \
0 -7.692167  0.176579  1.307491  16.582581 -0.638781   0.441933   

   Gender_Female  Gender_Male  Student_No  Student_Yes  Married_No  \
0       4.057786    -4.057786 -206.378065   206.378065    -0.24641   

   Married_Yes  Ethnicity_African American  Ethnicity_Asian  \
0      0.24641                   -13.97773        14.109205   

   Ethnicity_Caucasian  
0            -0.131475

In [29]:
reg.intercept_

array([-289.43593651])

In [30]:
y_pred = reg.predict(X_test)
y_val_pred= reg.predict(X_val)

In [31]:
mean_squared_error(y_test, y_pred)

12931.622590238989

In [32]:
mean_squared_error(y_val, y_val_pred)

9395.467791582905

In [34]:
y_train.mean()

500.859375

In [43]:
reg.coef_

array([[-7.69216711e+00,  1.76579219e-01,  1.30749140e+00,
         1.65825813e+01, -6.38781084e-01,  4.41933029e-01,
         4.05778593e+00, -4.05778593e+00, -2.06378065e+02,
         2.06378065e+02, -2.46409527e-01,  2.46409527e-01,
        -1.39777304e+01,  1.41092049e+01, -1.31474537e-01]])

O modelo ficou muito ruim para achar variaveis preditoras, vamos agora a abordagem de Lasso que já faz a feature selection

In [49]:
lasso = Lasso()

In [50]:
lasso.fit(X_train, y_train)

C:\Users\Samsung\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:492: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)


Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [51]:
y_pred = lasso.predict(X_test)
y_val_pred= lasso.predict(X_val)

In [52]:
lasso.coef_

array([-7.67190913e+00,  1.74895749e-01,  1.33023281e+00,  1.61492535e+01,
       -6.55856620e-01,  3.48685471e-01,  4.76164994e+00, -0.00000000e+00,
       -4.01246917e+02,  0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
       -9.72547726e+00,  1.02692219e+01, -0.00000000e+00])

In [54]:
mean_squared_error(y_test, y_pred)

12804.486612940298

In [55]:
mean_squared_error(y_val, y_val_pred)

9365.335683030738

In [56]:
y_train.mean()

500.859375

In [57]:
y_val.mean()

538.53125

In [58]:
y_test.mean()

566.5

In [59]:
y_train.describe()

count     256.000000
mean      500.859375
std       441.963555
min         0.000000
25%        49.250000
50%       459.500000
75%       835.250000
max      1999.000000
Name: Balance, dtype: float64

O modelo continua muito ruim mesmo apos a seleção de features

In [60]:
scaler = MinMaxScaler

In [62]:
scaler.fit(X, y)

AttributeError: 'DataFrame' object has no attribute '_reset'