# Exercicio 1

## Abra o banco de dados Boston e estime 3 regressões:

A primeira prevendo medv usando como preditor lstat;
A segunda prevendo medv usando como preditor age;
A terceira usando ambos os preditores.
O que podemos dizer sobre o comportamento dos coeficientes estimados? E sobre o ajuste dos modelos?

Estime uma regressão usando todas as variáveis como preditoras. Todas são úteis para prever medv? Quais você deixaria e quais tiraria? Por quê?

Como foi o ajuste desse modelo?

Agora tire as variáveis que você considerou que não ajudam a estimação de medv. O que aconteceu com o ajuste do modelo?

In [5]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [2]:
# Lendo os dados
boston = pd.DataFrame.from_csv("https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv")
boston.head()

C:\Users\Samsung\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  


zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
crim                                                                        
0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

              b  lstat  medv  
crim                          
0.00632  396.90   4.98  24.0  
0.02731  396.90   9.14  21.6  
0.02729  392.83   4.03  34.7  
0.03237  394.63   2.94  33.4  
0.06905  396.90   5.33  36.2

### Usando lstat

In [37]:
X = boston.lstat
y = boston.medv

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1 )
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print("Quantidade Observações:\nTreino: {tr}\nTeste: {te}\nValidação: {v}".format(tr = X_train.shape[0],
                                                                                 te = X_test.shape[0],
                                                                                 v = X_val.shape[0]))

Quantidade Observações:
Treino: 323
Teste: 102
Validação: 81


In [38]:
reg = LinearRegression()

In [39]:
reg.fit(X_train.values.reshape(-1,1), y_train.values.reshape(-1,1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [40]:
reg.coef_

array([[-0.93361049]])

In [41]:
reg.intercept_

array([34.5627696])

In [42]:
y_pred = reg.predict(X_test.values.reshape(-1,1))
y_val_pred= reg.predict(X_val.values.reshape(-1,1))

In [43]:
mean_squared_error(y_test, y_pred)

47.00985441342628

In [44]:
mean_squared_error(y_val, y_val_pred)

39.767436376214384

# Usando age

In [45]:
X = boston.age
y = boston.medv

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1 )
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print("Quantidade Observações:\nTreino: {tr}\nTeste: {te}\nValidação: {v}".format(tr = X_train.shape[0],
                                                                                 te = X_test.shape[0],
                                                                                 v = X_val.shape[0]))

Quantidade Observações:
Treino: 323
Teste: 102
Validação: 81


In [46]:
reg.fit(X_train.values.reshape(-1,1), y_train.values.reshape(-1,1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [47]:
reg.coef_

array([[-0.14128431]])

In [48]:
reg.intercept_

array([32.32148845])

In [49]:
y_pred = reg.predict(X_test.values.reshape(-1,1))
y_val_pred= reg.predict(X_val.values.reshape(-1,1))

In [50]:
mean_squared_error(y_test, y_pred)

94.84860436110552

In [51]:
mean_squared_error(y_val, y_val_pred)

74.8881577374661

## Usando age e lstat

In [54]:
X = boston[['age','lstat']]

In [56]:
y = boston.medv

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1 )
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print("Quantidade Observações:\nTreino: {tr}\nTeste: {te}\nValidação: {v}".format(tr = X_train.shape[0],
                                                                                 te = X_test.shape[0],
                                                                                 v = X_val.shape[0]))

Quantidade Observações:
Treino: 323
Teste: 102
Validação: 81


In [58]:
reg.fit(X_train, y_train.values.reshape(-1,1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [59]:
reg.coef_

array([[ 0.02477574, -0.99713034]])

In [60]:
reg.intercept_

array([33.6799168])

In [62]:
y_pred = reg.predict(X_test)
y_val_pred= reg.predict(X_val)

In [63]:
mean_squared_error(y_test, y_pred)

45.93015078827245

In [64]:
mean_squared_error(y_val, y_val_pred)

38.79576512255239

Podemos dizer que o modelo teve o melhor ajuste usando as duas variaveis como preditoras pois este apresentou o menor error nos dados de validação

## Utilizando todas variaveis como preditoras

In [73]:
X = boston

In [74]:
y = boston.medv

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1 )
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print("Quantidade Observações:\nTreino: {tr}\nTeste: {te}\nValidação: {v}".format(tr = X_train.shape[0],
                                                                                 te = X_test.shape[0],
                                                                                 v = X_val.shape[0]))

Quantidade Observações:
Treino: 323
Teste: 102
Validação: 81


In [75]:
reg.fit(X_train, y_train.values.reshape(-1,1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [76]:
reg.coef_

array([[-4.89709759e-17, -3.25196627e-17, -9.21196635e-17,
        -2.70298656e-14,  3.60673276e-15,  8.50442981e-17,
        -8.88932894e-16,  8.78433416e-16, -5.58119863e-17,
        -4.31314022e-16,  2.73931786e-16, -5.81144139e-16,
         1.00000000e+00]])

In [77]:
reg.intercept_

array([-6.03961325e-14])

In [78]:
y_pred = reg.predict(X_test)
y_val_pred= reg.predict(X_val)

In [79]:
mean_squared_error(y_test, y_pred)

6.45814127740935e-28

In [80]:
mean_squared_error(y_val, y_val_pred)

8.490675486293611e-28

Não tiraria nenhuma variavel pois obtemos um erro muito baixo nos dados de validação.

Variavel indus e age foram menos significativas

## Drop variaveis indus e age

In [84]:
X = boston.drop(columns = ['age', 'indus'])


In [86]:
y = boston.medv

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1 )
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)
print("Quantidade Observações:\nTreino: {tr}\nTeste: {te}\nValidação: {v}".format(tr = X_train.shape[0],
                                                                                 te = X_test.shape[0],
                                                                                 v = X_val.shape[0]))

Quantidade Observações:
Treino: 323
Teste: 102
Validação: 81


In [87]:
reg.fit(X_train, y_train.values.reshape(-1,1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [88]:
reg.intercept_

array([-6.00408612e-13])

In [89]:
reg.coef_

array([[ 2.08824160e-15, -9.64140167e-15, -3.49795050e-14,
        -2.51675935e-15,  5.37006603e-16, -1.02682513e-16,
         4.09271483e-16, -9.38239005e-17,  1.17703081e-15,
         4.11206655e-16,  1.00000000e+00]])

In [90]:
mean_squared_error(y_test, y_pred)

6.45814127740935e-28

In [91]:
mean_squared_error(y_val, y_val_pred)

8.490675486293611e-28

Retirar as variaveis não promoveu uma redução signifacativa nos erro para os dados de validação.